---
title: "Rayshader_proj"
author: "Jonathan Huang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Install Libraries
```{r}
library(tidyverse)
library(rayshader)
library(here)
library(elevatr) #elevation data
library()

```

#test
```{r}
montereybay %>%
  sphere_shade(zscale = 10, texture = "imhof1") %>%
  add_shadow(ray_shade(montereybay, zscale = 50)) %>%
  add_shadow(ambient_shade(montereybay, zscale = 50)) %>%
  plot_3d(montereybay, zscale = 50, theta = -45, phi = 45, water = TRUE,
          windowsize = c(1000,800), zoom = 0.75, waterlinealpha = 0.3,
          wateralpha = 0.5, watercolor = "lightblue", waterlinecolor = "white")
render_snapshot()
```


# Making our own map to work we need:

- image dimension match bounding box coordinate
- image dimension of elevation & map overlay needs to be the same dimension

To make our own map, we need 
```{r}
# define bounding box with longitude/latitude coordinates
bbox <- list(
  p1 = list(long = -122.522, lat = 37.707),
  p2 = list(long = -122.354, lat = 37.84)
)

image_size <- define_image_size(bbox, major_dim = 600)
```

