---
title: "moveVis Experimentation"
author: "Mac"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = "../output/")
```

I may be covering how to adapt frames

# Load Libraries

```{r}
library(moveVis)
library(move)
library(raster)
library(tidyverse)
library(ggplot2)
library(here)
library(tidytuesdayR)
library(lubridate)
library(janitor)
library(dplyr)
library(kableExtra)
library(maps)
library(mapdata)
library(mapproj)
```

# Load Data

```{r}
tuesdata <- tidytuesdayR::tt_load(2023, week = 5)

cats_uk <- as.data.frame(tuesdata$cats_uk) %>%
  mutate( timestamp = ymd_hms(timestamp)) %>%
  filter(tag_id %in% c("Athena","Ares", "Lola"))

cats_uk_reference <- tuesdata$cats_uk_reference

# use cats_uk
glimpse(cats_uk)
```

# Clean data

```{r}
cats_uk <- read_csv("https://www.datarepository.movebank.org/bitstream/handle/10255/move.883/Pet%20Cats%20United%20Kingdom.csv?sequence=3") %>%
  clean_names() %>%
  # Standardize things and reorder columns.
  select(tag_id = tag_local_identifier,
         event_id:location_lat,
         ground_speed,
         height_above_ellipsoid,
         algorithm_marked_outlier,
         manually_marked_outlier,
         study_name) %>%
  # Explicitly encode FALSE in the outlier columns.
  tidyr::replace_na(list(algorithm_marked_outlier = FALSE,
                         manually_marked_outlier = FALSE)) %>%
  # filter to have subset of data
  filter(tag_id %in% c("Athena","Ares","Lola"))

glimpse(cats_uk)

glimpse(cats_uk_reference)
```

# Data Analysis

```{r}
data("whitestork_data")

view(df)

m <- align_move(m, # This function filters to have consistent time scale so function frames_spatial
                res = 180, # change interval to every 30 min if 90; Can be "max" or "min" or "mean" for the average resolution
                digit = 0, # changes time interval in seconds
                unit = "mins")

view(m)

# df2move() #converts data.frame to move or movestack (data type needed) to add into :
# frames_spatial() OR frames_graph()

frames <- frames_spatial(m, # take move data
                         trace_show = TRUE,
                         equidistant = FALSE,
                         map_service = "osm", # select map
                         map_type = "terrain_bg")

frames[[200]] # plots a single frame

frames <- frames %>%
  add_labels(title = "White Storks (Ciconia ciconia) Migration 2018",
             caption = "Trajectory data: Cheng et al. (2019); Fiedler et al. (2013-2019), https://doi.org/10.5441/001/1.ck04mn78 Map: OpenStreetMap/Stamen; Projection: Geographic, WGS84",
             x = "Longitude",
             y = "Latitude") %>%
  add_timestamps(type = "label") %>% # can be "label" or "text"
  add_progress(colour = "white") %>%
  add_northarrow(colour = "white", position = "bottomleft") %>%
  add_scalebar(colour = "black", position = "bottomright", distance = 600)

frames[[200]] # plots a single frame

animate_frames(frames = frames, out_file = here("Mac","output","stork.gif"))
```

```{r}
# cats_uk %>% filter(tag_id %in% c("Athena","Ares", "Lola"))
# data need: tag_id - identifier
#          : x & y (i.e. Lat/long)
#          : time - make regular interval via 

# make df to move or movestack data

cats_uk <- cats_uk[!duplicated(cats_uk$timestamp),] # remove duplicate time stamp
test <- df2move(cats_uk,  #df
                proj = "+init=epsg:4326 +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0",  # type of projection
                x = "location_long",  # what are your x coord
                y = "location_lat",
                time = "timestamp", #what are the time, needs to be POSIXct
                track_id = "tag_id")

# align move to have same interval

m <- align_move(test,
                res = "mean",
                unit = "secs")

glimpse(m)

get_maptypes()

make_frames <- frames_spatial(m,
                              trace_show = TRUE, # show trace of complete path
                              equidistant = FALSE, # make map squared? FALSE= prevent stretching of map
                              map_service = "osm",   # select map type use ?get_maptypes
                              map_type = "mtb")

frames_aes <- make_frames %>%
  add_timestamps(type = "label") %>%  # show the timestamps
  add_progress(colour = "white") %>% # add a progress bar
  add_northarrow(colour = "white", position = "bottomleft") %>% 
  add_scalebar(colour = "black", position = "bottomright", distance = 600)

# check a single frame
make_frames[[100]]

animate_frames(frames = frames_aes, out_file = here("Mac","output","cattest2.gif"), overwrite = TRUE)
```

```{r}
data("move_data")

unique(timestamps(move_data))

timeLag(move_data, unit = "mins")

move_data <- align_move(move_data, res = 4, unit = "mins")

get_maptypes()

# Example 1

frames <- frames_spatial(move_data, path_colours = c("red", "green", "blue"),
                         map_service = "osm", map_type = "streets", alpha = 0.5)

length(frames) # number of frames

frames[[100]] # display one of the frames

animate_frames(frames, out_file = here("Mac", "output", "example_1.gif"), overwrite = TRUE)

# Example 2

frames <- frames_spatial(move_data, path_colours = c("red", "green", "blue"),
                         map_service = "osm", map_type = "streets", map_res = 0.8)

frames[[100]] # display one of the frames

move_data <- sp::spTransform(move_data, crs("+init=epsg:3857"))

frames <- frames_spatial(move_data, path_colours = c("red", "green", "blue"),
                         map_service = "osm", map_type = "streets", map_res = 0.8, equidistant = FALSE)

frames[[100]] # display one of the frames

animate_frames(frames, out_file = here("Mac", "output", "example_2.gif"), width = 700, height = 500, res = 80, overwrite = TRUE)
```

```{r}
data("move_data")

# align movement to unique times and regular resolution
m <- align_move(move_data, res = 4, unit = "mins")

## assign some path colours by individual
m.list <- split(m) # split m into list by individual

m.list <- mapply(x = m.list, y = c("red", "green", "blue"), function(x, y){
  x$colour <- y
  return(x)
}) # add colour per individual

m <- moveStack(m.list) # putting it back together into a moveStack

# create frames with mapbox satellite basemap
frames <- frames_spatial(m, map_service = "osm", map_type = "watercolor")

# animate the first 100 frames as example
animate_frames(frames[1:100], out_file = here("Mac", "output", "example_4.gif"), overwrite = TRUE)

# Example 5

# to not calculate a squared (enlarged) extent:
frames <- frames_spatial(m, map_service = "osm", map_type = "watercolor",
                         equidistant = FALSE)

ext <- extent(8.820289, 9.076893, 47.68715, 47.80863)

# set the ext argument
frames <- frames_spatial(m, map_service = "osm", map_type = "watercolor",
                         ext = ext, equidistant = FALSE) %>% 
  add_labels(x = "Longitude", y = "Latitude") %>% 
  add_northarrow(colour = "white", height = 0.08, position = "bottomleft") %>% 
  add_scalebar(colour = "white", height = 0.022, position = "bottomright", label_margin = 1.4) %>% 
  add_timestamps(m, type = "label")

# animate the first 100 frames as example
animate_frames(frames[1:100], out_file = here("Mac", "output", "example_5.gif"),
               height = 500, width = 800, res = 82, overwrite = TRUE)
```

# My version of the cat plot

```{r}
tuesdata <- tidytuesdayR::tt_load(2023, week = 5)

View(tuesdata$cats_uk)

glimpse(tuesdata$cats_uk)

selected_cats_v1 = c("Athena","Ares", "Lola", "Jago", "Maverick", "Charlie", "Coco", "Friday")

selected_cats_v2 = c("Athena","Ares", "Lola")

selected_cats_v3 = c("Lola", "Jago", "Maverick", "Charlie", "Coco", "Friday")

cats_uk <- as.data.frame(tuesdata$cats_uk) %>%
  mutate(timestamp = ymd_hms(timestamp)) %>%
  filter(tag_id %in% selected_cats_v1)

cats_uk_reference <- tuesdata$cats_uk_reference

cats_uk <- cats_uk[!duplicated(cats_uk$timestamp),] # remove duplicate time stamp

test <- df2move(
  cats_uk,  # df
  proj = "+init=epsg:4326 +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0",  # type of projection
  x = "location_long", # data mapped to x coordinates
  y = "location_lat", # data mapped to y coordinates
  time = "timestamp", # what are the time, needs to be POSIXct
  track_id = "tag_id"
  )

# You can use align_move to align the data to a uniform time scale
cats_m <- align_move(test, res = "mean", unit = "secs")

# You can use get_maptypes() get a list of all available map_services and map_types
get_maptypes()

# can use a custom extent
ext <- extent(-5.08, -5.06, 50.144, 50.160)

color_palette_v1 = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

color_palette_v2 = c("#999999", "#E69F00", "#56B4E9")

color_palette_v3 = c("#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# create spatial frames
frames <- frames_spatial(
  m = cats_m, # input data
  trace_show = TRUE, # show trace of complete path
  equidistant = FALSE, # make map square (FALSE = prevent stretching of map)
  map_service = "osm", # select map service
  map_type = "streets", # select map type
  alpha = 0.75, # select transparency level for map
  path_colours = color_palette_v1,
  # ext = ext,
  map_res = 1.0,
  )

length(frames) # number of frames

frames[[100]]

# edit spatial frames

frames <- add_labels(frames, x = "Longitude", y = "Latitude") # add labels, e.g. axis labels

frames[[100]]

frames <- add_timestamps(frames, type = "label") # show the timestamps

frames[[100]]

frames <- add_progress(frames, colour = "red") # add a progress bar

frames[[100]]

frames <- add_northarrow(frames, colour = "black", height = 0.08, position = "bottomleft") # add a north arrow

frames[[100]]

frames <- add_scalebar(frames, colour = "black", position = "bottomright", height = 0.022, label_margin = 1.4, distance = 1) # add a scalebar

frames[[100]]

# frames <- add_colourscale(frames)

# frames <- join_frames(frames)

# frames <- get_frametimes(frames)

data <- data.frame(x = c(-5.11, -5.10, -5.10, -5.11, -5.11),
                   y = c(50.160, 50.160, 50.165, 50.165, 50.160))

# just customize a single frame and have a look at it
frame_test <- frames[[100]] + geom_path(aes(x = x, y = y), data = data, colour = "red", linetype = "dashed")

# frame_test <- add_text(frame_test, "Static feature", x = -5.105, y = 50.159, colour = "black", size = 3)

frame_test

# or customize all frames at once using add_gg:
frames <- add_gg(frames, gg = expr(geom_path(aes(x = x, y = y), data = data, color = "red", linetype = "dashed")), data = data)

frames <- add_text(frames, "Static feature", x = -5.105, y = 50.159, colour = "black", size = 3)

# check one of the frames
frames[[100]]

# create data.frame containing corner coordinates
data <- data.frame(x = c(-5.08, -5.09, -5.09, -5.08, -5.08),
                   y = c(50.150, 50.150, 50.155, 50.155, 50.150))

# make a list from the data.frame by replicating it by the length of frames
data <- rep(list(data), length.out = length(frames))

# now alter the coordinates to make them shift
data <- lapply(data, function(x){
  y <- rnorm(nrow(x)-1, mean = 0.00001, sd = 0.0001) 
  x + c(y, y[1])
})

# draw each individual polygon to each frame
frames <- add_gg(frames, gg = expr(geom_path(aes(x = x, y = y), data = data, colour = "black")), data = data)

# add a text label
frames <- add_text(frames, "Dynamic feature", x = -5.085, y = 50.149, colour = "black", size = 3)

# Have a look at one of the frames:
frames[[100]]
```
```{r}
animate_frames(
  frames = frames,
  out_file = here("Mac", "output", "catplot.gif"),
  overwrite = TRUE,
  width = 700,
  height = 500,
  res = 80
  )
```

```{r}
animate_frames(
  frames = frames[1:10],
  out_file = here("Mac", "output", "catplot_10_frames.gif"),
  overwrite = TRUE,
  width = 700,
  height = 500,
  res = 80
  )
```
